export const allProjects = [
    {
        //fake commercial project
        id: 1,
        project_type: 'commercial',
        name: 'Company XYZ',
        location: 'Tacoma',
        image: '../images/Point-Ruston.jpg',
    },
    {
        id: 2,
        project_type: 'commercial',
        name: 'The Artisans Group',
        location: 'South Sound Region',
        image: '../images/artisans.jpg',
    },
    {
        id: 3,
        project_type: 'commercial',
        name: 'Les Schwab Tire Center',
        location: 'Centralia',
        image: '../images/les_schwab.jpg',
    },
    {
        id: 4,
        project_type: 'commercial',
        name: 'BP ARCO',
        location: 'South Sound Region',
        image: '../images/ARCO.jpg',
    },
    {
        id: 5,
        project_type: 'commercial',
        name: '7-Eleven',
        location: 'South Sound Region',
        image: '../images/7-eleven.png',
    },
    {
        //fake residence
        id: 6,
        project_type: 'residential',
        name: 'Smith Residence',
        location: 'Tacoma',
        image: '../images/residence_project.jpg',
    },
    {
        id: 7,
        project_type: 'residential',
        name: 'Gilbert Residence',
        location: 'Olympia',
        image: '../images/gilbert.jpeg',
    },
    {
        id: 8,
        project_type: 'residential',
        name: 'Wagner Residence',
        location: 'Olympia',
        image: '../images/wagner.jpg',
    },
    {
        id: 9,
        project_type: 'mixed-use',
        name: 'The Laurana',
        location: 'Olympia',
        image: '../images/Laurana_Article_Image.jpg',
    },
    {
        id: 10,
        project_type: 'hospitality',
        name: 'The Windjammer Hotel',
        location: 'Pacific Beach',
        image: '../images/windjammer.jpg',
    },
    {
        id: 10,
        project_type: 'hospitality',
        name: 'XYZ Hotel',
        location: 'Seattle',
        image: '../images/seattle.jpeg',
    },
];